from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
from langchain.memory import CassandraChatMessageHistory, ConversationBufferMemory
from langchain.llms import OpenAI
from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate
import json
import warnings

cloud_config= {
  'secure_connect_bundle': 'xxx'
}

# To stop langchain warning:
warnings.filterwarnings(action='ignore', category=UserWarning, module='langchain')

# This token JSON file is autogenerated when you download your token, 
# if yours is different update the file name below
with open("xxx") as f:
    secrets = json.load(f)

CLIENT_ID = secrets["clientId"]
CLIENT_SECRET = secrets["secret"]
ASTRA_DB_KEYSPACE = ""
OPENAI_API_KEY    = ""


auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
session = cluster.connect()

message_history = CassandraChatMessageHistory(
    session_id="my-chat",
    session=session,
    keyspace=ASTRA_DB_KEYSPACE,
    ttl_seconds=3600
)
# To get a new instance of memory every time the app is run
message_history.clear()

# To make it easier for us to load this into the OpenAI prompt
cass_buff_memory = ConversationBufferMemory(
    memory_key="chat_history",
    chart_memory=message_history
)
template = """
You are now the guide of a mystical journey in the Whispering Woods. 
A traveler named Elara seeks the lost Gem of Serenity. 
You must navigate her through challenges, choices, and consequences, 
dynamically adapting the tale based on the traveler's decisions. 
Your goal is to create a branching narrative experience where each choice 
leads to a new path, ultimately determining Elara's fate. 

Here are some rules to follow:
1. Start by asking the player to choose some kind of weapons that will be used later in the game
2. Have a few paths that lead to success
3. Have some paths that lead to death. If the user dies generate a response that explains the death and ends in the text: "The End.", I will search for this text to end the game

Here is the chat history, use this to understand what to say next: {chat_history}
Human: {human_input}
AI:"""

prompt = PromptTemplate(
    input_variables=["chat_history", "human_input"],
    template=template
)

# To initialize a connection with OpenAI
llm = OpenAI(openai_api_key=OPENAI_API_KEY)

# To initialize the chain and connect to our LLM. 
llm_chain = LLMChain(
    llm=llm,
    prompt=prompt,
    memory=cass_buff_memory
)
choice = "start"

while True:
    response = llm_chain.predict(human_input=choice)
    # print the response and strip any white spaces or new characters the llm might introduce
    print(response.strip())
    if "The End." in response:
        break
    choice = input("Your reply: ")


